name = "macswap"
secondary = false
primary_core = 0
cores = [0, 1]
strict = false
pool_size = 512
cache_size = 32
duration = 0
[[ports]]
  name = "0000:02:00.0"
  rx_queues = [0, 1]
  tx_queues = [0, 1]
  rxd = 128
  txd = 128
  loopback = false
  tso = false
  csum = false